-- ==============================================
-- Import mlpn.pl 2018-2025 (Part 5: Setup)
-- 71 drużyn, 2907 meczów
-- Uruchom PO part1-part4 (archiwum)
-- ==============================================

BEGIN;

-- Sezony 2018-2025
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2018', 2018, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2019', 2019, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2020', 2020, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2021', 2021, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2022', 2022, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2023', 2023, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2024', 2024, 'completed') ON CONFLICT (year) DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2025', 2025, 'active') ON CONFLICT (year) DO NOTHING;

-- Drużyny (nowe z 2018-2025)
INSERT INTO teams (name, abbreviation, is_active) VALUES ('-przerwa-', 'PRZER', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/Pauza-150x150.png' WHERE name = '-przerwa-' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('0 - 3', '0  3', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('1 Warszawska Brygada Pancerna', '1 WAR', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/1-Warszawska-Brygada-Pancerna-150x150.png' WHERE name = '1 Warszawska Brygada Pancerna' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('2 - 12', '2  12', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Al Mar Wołomin', 'AL MA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2023/03/almar-removebg-preview-2-150x150.png' WHERE name = 'Al Mar Wołomin' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('AL-Komat', 'ALKOM', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/teams_st.png' WHERE name = 'AL-Komat' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Alchemia Futbolu', 'ALCHE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/alchemia-removebg-preview-150x150.png' WHERE name = 'Alchemia Futbolu' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Avanti', 'AVANT', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_chaosteam-150x150.png' WHERE name = 'Avanti' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Chaos Team', 'CHAOS', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/received_166413826282361-removebg-preview-150x150.png' WHERE name = 'Chaos Team' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('D.T. Galacticos', 'DT GA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_glacticos-1-150x150.png' WHERE name = 'D.T. Galacticos' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Dar Mar', 'DAR M', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2022/03/darmar-removebg-preview-150x150.png' WHERE name = 'Dar Mar' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Detox', 'DETOX', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/detox-150x150.png' WHERE name = 'Detox' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Detox U23', 'DETO2', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_detoxu23-150x150.png' WHERE name = 'Detox U23' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Dziady', 'DZIAD', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/teams_st.png' WHERE name = 'Dziady' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Elo Melo', 'ELO M', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/received_3260333964217011-removebg-preview-150x150.png' WHERE name = 'Elo Melo' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Es Chobot Meat', 'ES CH', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/ES-CHOBOT-MEAT-150x150.png' WHERE name = 'Es Chobot Meat' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Faludża', 'FALUD', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2025/03/faludza-150x150.png' WHERE name = 'Faludża' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fanatycy', 'FANAT', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/fanatycy1-150x150.png' WHERE name = 'Fanatycy' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Bartycka 04', 'FC BA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/teams_st.png' WHERE name = 'FC Bartycka 04' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fc Faworyt', 'FC FA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/received_1714700332265687-removebg-preview-1-150x150.png' WHERE name = 'Fc Faworyt' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fc International', 'FC IN', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_magnatt-150x150.png' WHERE name = 'Fc International' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fc KSS', 'FC KS', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2023/03/kss-1-150x150.jpg' WHERE name = 'Fc KSS' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fc Legion', 'FC LE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_walencja-150x150.png' WHERE name = 'Fc Legion' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC MBM', 'FC MB', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_fcmbm-150x150.png' WHERE name = 'FC MBM' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Podbudowani', 'FC PO', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2022/09/fc-podbudowani-150x150.png' WHERE name = 'FC Podbudowani' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fc Zieloni', 'FC ZI', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_fczieloni-150x150.png' WHERE name = 'Fc Zieloni' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Gold Dent P.T.', 'GOLD', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_golddent-150x150.png' WHERE name = 'Gold Dent P.T.' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Gosuansa', 'GOSUA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_fcmbm-150x150.png' WHERE name = 'Gosuansa' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Green Team', 'GREEN', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2020/08/LOGO-removebg-preview-150x150.png' WHERE name = 'Green Team' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Hard Impet Team', 'HARD', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2020/08/IMG_20230328_115139-removebg-preview-150x150.png' WHERE name = 'Hard Impet Team' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Hardcore Team', 'HARDC', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_hardcore-150x150.png' WHERE name = 'Hardcore Team' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Huragan', 'HURAG', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/huragan-sjk-150x150.png' WHERE name = 'Huragan' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Huragan Poręby Nowe', 'HURA2', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/20230930_200250_0000-removebg-preview-150x150.png' WHERE name = 'Huragan Poręby Nowe' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Impet', 'IMPET', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_impet-150x150.png' WHERE name = 'Impet' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Joga Finito', 'JOGA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/joga-finito-150x150.png' WHERE name = 'Joga Finito' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('KOMINKI SIM – Pianka Kuflew', 'KOMIN', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_kominkisim-150x150.png' WHERE name = 'KOMINKI SIM – Pianka Kuflew' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('KS ProBram24', 'KS PR', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2019/03/IMG_20230922_110808-removebg-preview-1-150x150.png' WHERE name = 'KS ProBram24' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Legioholicy', 'LEGIO', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/legia-warszawa-logo-C099211EA6-seeklogo.com_-150x150.png' WHERE name = 'Legioholicy' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Lider', 'LIDER', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/lider-removebg-preview-2-150x150.png' WHERE name = 'Lider' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Magnatt.eu', 'MAGNA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_golddent-150x150.png' WHERE name = 'Magnatt.eu' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Multi-Medica Zielonka', 'MULTI', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_medica-150x150.png' WHERE name = 'Multi-Medica Zielonka' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nankatsu', 'NANKA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/nankatsu-removebg-preview-150x150.png' WHERE name = 'Nankatsu' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('New Team FC', 'NEW T', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/New-Team-FC-150x150.png' WHERE name = 'New Team FC' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('No Name', 'NO NA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_noname-150x150.png' WHERE name = 'No Name' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nowa Południowa Afryka', 'NOWA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_npa-150x150.png' WHERE name = 'Nowa Południowa Afryka' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Olcskul', 'OLCSK', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_olcskul-150x150.png' WHERE name = 'Olcskul' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Oldrembham Forest', 'OLDRE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_fczieloni-150x150.png' WHERE name = 'Oldrembham Forest' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Olympique Zgon', 'OLYMP', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2020/09/zgon-removebg-preview-1.png' WHERE name = 'Olympique Zgon' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Panika Papryka', 'PANIK', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_panikapapryka-150x150.png' WHERE name = 'Panika Papryka' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Panpierożek.pl', 'PANPI', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_panpierozek-150x150.png' WHERE name = 'Panpierożek.pl' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PJM', 'PJM', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_pjm-150x150.png' WHERE name = 'PJM' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PKKL Pierożek', 'PKKL', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_pjm-150x150.png' WHERE name = 'PKKL Pierożek' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PKKL Sulejówek', 'PKKL2', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_pkkl-150x150.png' WHERE name = 'PKKL Sulejówek' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('przerwa', 'PRZE2', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/Pauza-150x150.png' WHERE name = 'przerwa' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Putkersi', 'PUTKE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_fcfaworyt-150x150.png' WHERE name = 'Putkersi' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Rebelianci', 'REBEL', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/Rebelianci-150x150.png' WHERE name = 'Rebelianci' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('SC Halinów', 'SC HA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2021/04/sc-halinow3-1-150x150.png' WHERE name = 'SC Halinów' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sfinks', 'SFINK', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_sfinks-150x150.png' WHERE name = 'Sfinks' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sparta', 'SPART', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_sparta-150x150.png' WHERE name = 'Sparta' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sportowe Zakapiory', 'SPORT', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2021/04/Sportowe-Zakapiory-150x150.png' WHERE name = 'Sportowe Zakapiory' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Stara Ekipa', 'STARA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_staraekipa-150x150.png' WHERE name = 'Stara Ekipa' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Starszaki', 'STARS', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/starszaki-150x150.png' WHERE name = 'Starszaki' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('STM FC', 'STM F', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2024/03/STM-FC-150x150.png' WHERE name = 'STM FC' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Tęcza Pustelnik', 'TĘCZA', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/03/tecza-removebg-preview-150x150.png' WHERE name = 'Tęcza Pustelnik' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Tidy Team', 'TIDY', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2021/04/TIDY-TEAM-1-150x150.png' WHERE name = 'Tidy Team' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Tiger Wołomin', 'TIGER', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2021/04/tiger-150x150.png' WHERE name = 'Tiger Wołomin' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('v', 'V', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Walencja', 'WALEN', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2018/04/koszulka_walencja-150x150.png' WHERE name = 'Walencja' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('wolne miejsce II', 'WOLNE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/teams_st.png' WHERE name = 'wolne miejsce II' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('xxx', 'XXX', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/teams_st.png' WHERE name = 'xxx' AND logo_url IS NULL;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Zerzeńskie Pegazy', 'ZERZE', true) ON CONFLICT (name) DO NOTHING;
UPDATE teams SET logo_url = 'http://mlpn.plhttp://mlpn.pl/wp-content/uploads/2022/03/zerzenskie-pegazy2-150x150.png' WHERE name = 'Zerzeńskie Pegazy' AND logo_url IS NULL;

COMMIT;