-- ==============================================
-- Import archiwum MLPN 2003-2017
-- Wygenerowano automatycznie z plików L98
-- 41 plików, 142 drużyn, 5333 meczów
-- ==============================================

BEGIN;

-- Ligi (użyj istniejących jeśli są)
INSERT INTO leagues (name, code, display_order) VALUES ('I Liga', '1st', 1) ON CONFLICT DO NOTHING;
INSERT INTO leagues (name, code, display_order) VALUES ('II Liga', '2nd', 2) ON CONFLICT DO NOTHING;
INSERT INTO leagues (name, code, display_order) VALUES ('III Liga', '3rd', 3) ON CONFLICT DO NOTHING;

-- Sezony archiwalne
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2003', 2003, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2004', 2004, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2005', 2005, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2006', 2006, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2007', 2007, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2008', 2008, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2009', 2009, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2010', 2010, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2011', 2011, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2012', 2012, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2013', 2013, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2014', 2014, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2015', 2015, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2016', 2016, 'completed') ON CONFLICT DO NOTHING;
INSERT INTO seasons (name, year, status) VALUES ('Sezon 2017', 2017, 'completed') ON CONFLICT DO NOTHING;

-- Drużyny (unikalne)
INSERT INTO teams (name, abbreviation, is_active) VALUES ('A-Team', 'ATEAM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Alabama', 'ALABA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Alchemia Futbolu', 'ALF', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Auto-Pol Team', 'APT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Bałtyk Miłosna', 'BAŁT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Białowieska', 'BIA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('C Klasa', 'C KLA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Chaos Team', 'CHAOS', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Colgate', 'COLG', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Colgate Palmolive', 'COLG2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Colgate-Palmolive Poland', 'COLG3', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Cyganka', 'CYG', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Derejn', 'DEREJ', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Detox', 'DETOX', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Devils Wołomin', 'WOŁOM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('DKL Żurawka', 'ŻURAW', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Długa i Michałów', 'DIM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Długa Szlachecka', 'DŁUGA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Długa Team', 'DŁUG2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Dragon''s', 'DRAGO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Drink Team', 'DRINK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('DT Galacticos', 'DTG', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Dziadki', 'DZIAD', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('EL Brygada', 'EB', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Elo Melo', 'ELO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Eurotherm Walencja', 'EW', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Fanatycy', 'FAN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC', 'FCSUL', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Belfast', 'BELF', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Białowieska', 'BIA2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Bravado', 'BRAVA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Centurio', 'CENTU', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Faworyt', 'FCF', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Faworyt Anwa-Tech', 'FAWOR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Kolejniak', 'KOLEJ', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Kosmos', 'KOSMO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Marino', 'MARIN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Nieobliczalni', 'NIE', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Zakręt', 'ZAKR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FC Zieloni', 'ZIE', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FIFA Squad', 'FIFA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('FIFA&Ślimak', 'FIFA2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Filmweb.pl', 'FILM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Global', 'GLOB', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Gold Dent', 'GD', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Gold-Dent PT', 'GD2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('GOLD-DENT.P.T LECZNICA STOMATOLOGICZNA', 'GOL', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Gosuansa', 'GOSU', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Grafix Bis STM', 'STM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Hardcore PZU', 'HAR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Hardcore Team', 'HT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Huragan Poręby Nowe', 'HUR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Husaria', 'HUSUL', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Husaria Hipolitów', 'HUSAR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Hydro Instal Wołomin', 'HYDRO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Impet', 'IMPET', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Iniemamocni', 'INI', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Inter Trade', 'INTER', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Joga Finito', 'JOGA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('KERAM Los Torpedos', 'LT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('KKP Grabaż', 'GRABA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Kominki Sim Pianka Kuflew', 'KSPK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Korsarze', 'KORSA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Kortbud Okuniew', 'KORT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('KP Żurawka', 'ŻURA2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Legioholicy', 'LEGIO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Legioholicy 2003', 'L2003', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Legioholicy II', 'LEG 2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Lider', 'LIDER', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('LO', 'LOS', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Los Torpedos', 'LT2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Majtom', 'MAJTO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('MBM Kebab', 'MBM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('MDT', 'MDT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Michałów', 'MICH', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('MKS Halinów', 'MKS', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Młoda Gwardia', 'MG', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Młode Żółwie Ninja', 'MŻN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Mordor Team', 'MOR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Multi-Medica Zielonka', 'MMZ', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nafta Team', 'NT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nankatsu', 'NAN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Napaciapani', 'NAP', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nowa drużyna', 'ND', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Nowa Południowa Afryka', 'NPA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Okinawa', 'OKI', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Okuniew', 'OKUN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Olcskul', 'OLC', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Orły Stara Miłosna', 'OSM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('P&V', 'P&V', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pan Pierożek', 'PP', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pan Pierożek.pl', 'PIE', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Panika Papryka', 'PP2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pędzące Żółwie', 'PŻÓŁW', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pędzący Kombajn', 'PK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pętla Team', 'PĘTLA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Phenian Club', 'PHEN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pianka Kuflew', 'PIAN', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pianka Kuflew Kominkisim', 'PIAN2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pianka Kuflew Kominkisim.pl', 'PIAN3', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PJM', 'PJM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PKKL', 'PKKL', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pogoń Okuniew', 'POGOŃ', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Polutil Rządza', 'POLUT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pomeczu', 'POMEC', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Posch Titanium', 'POSCH', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pradziadki', 'PRA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Prawie Jak Mistrz', 'PJM2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Promil Czarniecki', 'PROM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Pts Lzs Tęcza Pustelnik', 'PLTP', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('PTS Tęcza Pustelnik', 'TP', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Putka Team', 'PUTKA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Rebelianci', 'REB', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Repra', 'REPRA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Revolta', 'REV', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sami Swoi', 'SS', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Samograj', 'SAMOG', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Samogray', 'SAMO2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('San Faworyt', 'SFAW', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('San Marino', 'SM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sfinks', 'SFINK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Siwe Bobki', 'SIWEB', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Slimak.com.pl', 'SLIM', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('SM Joga Finito', 'SMJF', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Sparta', 'SPA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Stankan', 'STA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Starszaki', 'STAR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Starszaki II', 'STAR2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Starszaki Nieruchomości Belweder', 'STAR3', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Stm Team', 'STM2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Szakale', 'SZAK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Szakale Józefin', 'SZAK2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Teknosystem', 'TEKNO', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Tęcza Pustelnik', 'TP2', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Viking', 'VIK', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Walencja', 'WAL', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Wenus', 'WENUS', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Wichura', 'WICH', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('WMR', 'WMR', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('WSNT', 'WSNT', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Zabraniec', 'ZABRA', true) ON CONFLICT (name) DO NOTHING;
INSERT INTO teams (name, abbreviation, is_active) VALUES ('Zakład Mięsny Miśko', 'ZMM', true) ON CONFLICT (name) DO NOTHING;

COMMIT;
